#ifndef __OCARINA_GENERATED_ACTIVITY_H_
#define __OCARINA_GENERATED_ACTIVITY_H_ 
#include <request.h>
/*****************************************************/

/*  This file was automatically generated by Ocarina */

/*  Do NOT hand-modify this file, as your            */

/*  changes will be lost when you re-run Ocarina     */

/*****************************************************/

void producera_deliver 
    (__po_hi_request_t* request);

void* producera_job (void);

void result_consumera_deliver 
    (__po_hi_request_t* request);

void* result_consumera_job (void);

void consumerb_deliver 
    (__po_hi_request_t* request);

void* consumerb_job (void);

void result_producerb_deliver 
    (__po_hi_request_t* request);

void* result_producerb_job (void);

void __po_hi_main_deliver 
    (__po_hi_request_t* request);

#endif
