#include "subprograms.h"
#include <types.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
void user_produce_spg 
    (software__alpha_type* data_source);
void software__produce_spg 
    (software__alpha_type* data_source)
{

  user_produce_spg (data_source);
}

void user_consume_spg 
    (software__alpha_type data_sink);
void software__consume_spg 
    (software__alpha_type data_sink)
{

  user_consume_spg (data_sink);
}


